// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/scenepulse-ios-theme/LightMode.tsx": () => import("../components/mockups/scenepulse-ios-theme/LightMode.tsx")
};
